### PR TITLE
Checking IsLeader instead of ClusterAddress.

### LINKED ISSUE #3: Determining leader
Hello and thanks for creating this project.

We tried using the agent in our setup, but could not get it to create snapshots even though the agent was on the leader node.
After some digging I found out how you determine if the agent is running on the leader node by checking against 8.8.8.8 with the function [getInstanceIP()](https://github.com/Lucretius/vault_raft_snapshot_agent/blob/master/main.go#L110)
The issue we faced is that we don't use IPs to reference our nodes, but instead use DNS registered names (for TLS to work)

My question is:
Is there is a reason you get node IP and compare it to LeaderClusterAddress rather than just checking the [IsSelf ](https://github.com/hashicorp/vault/blob/master/api/sys_leader.go#L23)value.
This of course assumes you query the nodes local api_addr.

Thanks again
// Jonathan

### PR DESCRIPTION
**Pull request by Kyrklund**
Checking "**IsLeader**" instead of "**ClusterAddress**", which returns true or false when asking local/specific node.
Tested and verified in HA Vault Cluster
Removed unused function that checks google dns for local node IP. Also removed packages that are not used with new way of determining Leader

Closes #3

### CODE REVIEW

**Comment by Lucretius** [comment]
Just saw this PR, it looks good I'll try to get it released soon

**Comment by Kyrklund** [comment]
In our setup we had `addr`  set to the local nodes address. On server1 it is set to: `server1.example.com` and on server2  to: `server1.example.com`

**Comment by Lucretius** [comment]
I see - so it sounds like we just need to make it optional (since by default it resolves to `127.0.0.1`) and then call that out in the documentation.  After that, this should be good to go.

**Comment by LouisNitag** [comment]
Any news about it?

**Comment by Lucretius** [comment]
Let me merge this in, sorry about the delay

**Pull request merged**
